### PR TITLE
Use udevadm instead of udevd

### PR DESCRIPTION
**Pull request by scribblemaniac**
See #54.

Includes the changes from #53 so that I could run the Travis tests on the update, so this should be pulled after or instead of #53.

### CODE REVIEW

**Comment by gonzalo** [comment]
Overrided the #53 pull request with this. Thanks a lot @scribblemaniac

**Comment by gonzalo** [comment]
Can you add some instructions about how to use Travis tests?

**Comment by gonzalo** [comment]
Ok, not necessary, running my first Travis test!!. That's an amazing feature @scribblemaniac !! Exactly what we need for this project and very useful for other I have in mind

Thanks a lot!!

**Comment by scribblemaniac** [comment]
Glad to see you figured it out, I'm happy to help! I just recently learned how to use Travis myself, and I thought that this would be an excellent place to use it.

**Pull request merged**
